server:
  port: 8081

spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health

thread:
  pool:
    size: 3

clients:
  track:
    api:
      url: http://container1/track
    timeout: 5

  shipments:
    api:
      url: http://container1/shipments
    timeout: 5

  pricing:
    api:
      url: http://container1/pricing
    timeout: 5

slaEnforcement:
  defaultThreshold: 10000

batch:
  size: 5
