thread:
  pool:
    size: 3

clients:
  track:
    api:
      url: http://localhost:8080/track
    timeout: 5

  shipments:
    api:
      url: http://localhost:8080/shipments
    timeout: 5

  pricing:
    api:
      url: http://localhost:8080/pricing
    timeout: 5

slaEnforcement:
  defaultThreshold: 10000

batch:
  size: 5
